theme: jekyll-theme-minimal
title: Viviane Franco
description: "IA na Educação"
show_downloads: false

# Links para redes sociais
github: vivianefranco
linkedin: Viviane Franco
email: "vivianefrancodasilva@gmail.com"

# Configuração para habilitar posts
include: ["_posts"]

